function showTab(t, e){document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));document.getElementById(t).classList.add('active');e.target.classList.add('active');}
function closeModal(){document.getElementById('addModal').classList.remove('active');}
function showAddModal(){document.getElementById('modalTitle').textContent='Add New';document.getElementById('modalBody').innerHTML='<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;"><button class="btn btn-primary" onclick="showAddCompany()">🏢 Company</button><button class="btn btn-primary" onclick="showAddContact()">👥 Contact</button><button class="btn btn-primary" onclick="showAddDealModal('Lead')">📋 Deal</button><button class="btn btn-primary" onclick="showAddCandidate()">👔 Candidate</button></div>';document.getElementById('addModal').classList.add('active');}
function showAddCompany(){document.getElementById('modalTitle').textContent='Add Company';document.getElementById('modalBody').innerHTML='<form onsubmit="saveCompany(event)"><div class="form-group"><label class="form-label">Company Name</label><input type="text" name="name" class="form-input" required></div><div class="form-row"><div class="form-group"><label class="form-label">Sector</label><input type="text" name="sector" class="form-input"></div><div class="form-group"><label class="form-label">Location</label><input type="text" name="location" class="form-input"></div></div><div class="form-group"><label class="form-label">Active Projects</label><input type="text" name="active_projects" class="form-input"></div><div class="form-group"><label class="form-label">Tier</label><select name="tier" class="form-select"><option value="Tier 2">Tier 2</option><option value="Tier 1">Tier 1</option></select></div><div class="form-actions"><button type="button" class="btn btn-secondary" onclick="showAddModal()">Back</button><button type="submit" class="btn btn-primary">Save</button></div></form>';}
function saveCompany(e){e.preventDefault();const f=e.target;fetch('http://localhost:8081/api/company',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.name.value,sector:f.sector.value,location:f.location.value,active_projects:f.active_projects.value,tier:f.tier.value})}).then(r=>r.json()).then(d=>{alert('Company added!');location.reload();}).catch(e=>alert('Error: '+e));}
function showAddContact(){document.getElementById('modalTitle').textContent='Add Contact';document.getElementById('modalBody').innerHTML='<form onsubmit="saveContact(event)"><div class="form-group"><label class="form-label">Name</label><input type="text" name="contact_name" class="form-input" required></div><div class="form-group"><label class="form-label">Company</label><input type="text" name="company" class="form-input" required></div><div class="form-row"><div class="form-group"><label class="form-label">Type</label><select name="type" class="form-select"><option value="Decision Maker">Decision Maker</option><option value="Hiring Manager">Hiring Manager</option><option value="HR">HR</option></select></div><div class="form-group"><label class="form-label">Score</label><input type="number" name="relationship_score" class="form-input" value="5" min="1" max="10"></div></div><div class="form-group"><label class="form-label">Email</label><input type="email" name="email" class="form-input"></div><div class="form-group"><label class="form-label">Phone</label><input type="text" name="phone" class="form-input"></div><div class="form-actions"><button type="button" class="btn btn-secondary" onclick="showAddModal()">Back</button><button type="submit" class="btn btn-primary">Save</button></div></form>';}
function saveContact(e){e.preventDefault();const f=e.target;fetch('http://localhost:8081/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contact_name:f.contact_name.value,company:f.company.value,type:f.type.value,relationship_score:parseInt(f.relationship_score.value),email:f.email.value,phone:f.phone.value})}).then(r=>r.json()).then(d=>{alert('Contact added!');location.reload();}).catch(e=>alert('Error: '+e));}
function showAddDealModal(stage){document.getElementById('modalTitle').textContent='Add Deal';document.getElementById('modalBody').innerHTML='<form onsubmit="saveDeal(event)"><input type="hidden" name="stage" value="'+stage+'"><div class="form-group"><label class="form-label">Client/Company</label><input type="text" name="client" class="form-input" required></div><div class="form-group"><label class="form-label">Role</label><input type="text" name="role" class="form-input" placeholder="e.g. Project Manager"></div><div class="form-row"><div class="form-group"><label class="form-label">Fee ($)</label><input type="number" name="fee_value" class="form-input"></div><div class="form-group"><label class="form-label">Prob (%)</label><input type="number" name="probability" class="form-input" value="20" min="1" max="100"></div></div><div class="form-actions"><button type="button" class="btn btn-secondary" onclick="showAddModal()">Back</button><button type="submit" class="btn btn-primary">Save</button></div></form>';}
function saveDeal(e){e.preventDefault();const f=e.target;fetch('http://localhost:8081/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client:f.client.value,role:f.role.value,stage:f.stage.value,fee_value:parseInt(f.fee_value.value)||0,probability:parseInt(f.probability.value)||20})}).then(r=>r.json()).then(d=>{alert('Deal added!');location.reload();}).catch(e=>alert('Error: '+e));}
function showAddCandidate(){document.getElementById('modalTitle').textContent='Add Candidate';document.getElementById('modalBody').innerHTML='<form onsubmit="saveCandidate(event)"><div class="form-group"><label class="form-label">Name</label><input type="text" name="name" class="form-input" required></div><div class="form-group"><label class="form-label">Title</label><input type="text" name="title" class="form-input"></div><div class="form-row"><div class="form-group"><label class="form-label">Current Company</label><input type="text" name="current_company" class="form-input"></div><div class="form-group"><label class="form-label">Years Exp</label><input type="number" name="years_experience" class="form-input"></div></div><div class="form-group"><label class="form-label">Specialism</label><input type="text" name="specialism" class="form-input"></div><div class="form-group"><label class="form-label">Salary Band</label><input type="text" name="salary_band" class="form-input"></div><div class="form-actions"><button type="button" class="btn btn-secondary" onclick="showAddModal()">Back</button><button type="submit" class="btn btn-primary">Save</button></div></form>';}
function saveCandidate(e){e.preventDefault();const f=e.target;fetch('http://localhost:8081/api/candidate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.name.value,title:f.title.value,current_company:f.current_company.value,years_experience:parseInt(f.years_experience.value)||0,specialism:f.specialism.value,salary_band:f.salary_band.value})}).then(r=>r.json()).then(d=>{alert('Candidate added!');location.reload();}).catch(e=>alert('Error: '+e));}
function viewCompany(id){window.open('http://localhost:8081/company/'+id,'_blank');}
function viewContact(id){window.open('http://localhost:8081/contact/'+id,'_blank');}
function viewDeal(id){window.open('http://localhost:8081/deal/'+id,'_blank');}
function viewCandidate(id){window.open('http://localhost:8081/candidate/'+id,'_blank');}
